# Generated by Django 6.0.6 on 2026-08-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
